name: finance_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  awesome_dialog: ^3.2.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  bloc: ^8.1.4
  build_runner: ^2.4.9
  colorize: ^3.0.0
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  fancy_shimmer_image: ^2.0.3
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.5
  hexcolor: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  meta: ^1.10.0
  path_provider: ^2.1.3
  flutter_native_splash: ^2.4.1
  syncfusion_flutter_charts: ^27.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#799351"
  image: "assets/images/app_icon.png"
